name: Cypress tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Gestao-de-Metas:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}  
            CYPRESS_USERNAME_CEO: ${{ secrets.CYPRESS_USERNAME_CEO }}
            CYPRESS_USERNAME_VICEPRESIDENTE: ${{ secrets.CYPRESS_USERNAME_VICEPRESIDENTE }}
            CYPRESS_USERNAME_DIRETORCRA: ${{ secrets.CYPRESS_USERNAME_DIRETORCRA }}
            CYPRESS_USERNAME_DIRETORADMISSAOAODESLIGAMENTO: ${{ secrets.CYPRESS_USERNAME_DIRETORADMISSAOAODESLIGAMENTO }}
            CYPRESS_USERNAME_DIRETORADJDESERVICOSFINANCEIROS: ${{ secrets.CYPRESS_USERNAME_DIRETORADJDESERVICOSFINANCEIROS }}
            CYPRESS_USERNAME_DIRETORADJDEFECHAMENTOAOREPORTE: ${{ secrets.CYPRESS_USERNAME_DIRETORADJDEFECHAMENTOAOREPORTE}}
            CYPRESS_USERNAME_DIRETOR_A_JURIDICO: ${{ secrets.CYPRESS_USERNAME_DIRETOR_A_JURIDICO}}
            CYPRESS_USERNAME_DIRETOR_A_DEMARKETING: ${{ secrets.CYPRESS_USERNAME_DIRETOR_A_DEMARKETING }}
            CYPRESS_USERNAME_DIRETOR_A_DETI: ${{ secrets.CYPRESS_USERNAME_DIRETOR_A_DETI }} 
            CYPRESS_USERNAME_DIRETOREAD: ${{ secrets.CYPRESS_USERNAME_DIRETOREAD }} 
            CYPRESS_USERNAME_DIRETORDEOPERACOESACADEMICAS: ${{ secrets.CYPRESS_USERNAME_DIRETORDEOPERACOESACADEMICAS }}
            CYPRESS_USERNAME_DIRETORDEPROGRAMASESTUDANTIS: ${{ secrets.CYPRESS_USERNAME_DIRETORDEPROGRAMASESTUDANTIS }}
            CYPRESS_USERNAME_DIRETORDEREGULACAO: ${{ secrets.CYPRESS_USERNAME_DIRETORDEREGULACAO }} 
            CYPRESS_USERNAME_DIRETORADJDEREGULACAOPESQUISAEEXTENSAO: ${{ secrets.CYPRESS_USERNAME_DIRETORADJDEREGULACAOPESQUISAEEXTENSAO }}
            CYPRESS_USERNAME_CFO: ${{ secrets.CYPRESS_USERNAME_CFO }}
            CYPRESS_USERNAME_DIRETORAADMINISTRATIVA: ${{ secrets.CYPRESS_USERNAME_DIRETORAADMINISTRATIVA }}
            CYPRESS_USERNAME_DIRETOR_A_DERECURSOSHUMANOS: ${{ secrets.CYPRESS_USERNAME_DIRETOR_A_DERECURSOSHUMANOS }}
            CYPRESS_USERNAME_GERENTEDEPROCESSAMENTO: ${{ secrets.CYPRESS_USERNAME_GERENTEDEPROCESSAMENTO }}
            CYPRESS_USERNAME_GERENTEDEATENDIMENTO: ${{ secrets.CYPRESS_USERNAME_GERENTEDEATENDIMENTO }}
            CYPRESS_USERNAME_GERENTEA: ${{ secrets.CYPRESS_USERNAME_GERENTEA }}
            CYPRESS_USERNAME_GERENTEB: ${{ secrets.CYPRESS_USERNAME_GERENTEB }}
            CYPRESS_USERNAME_GERENTEDERECURSOSFINANCEIROS: ${{ secrets.CYPRESS_USERNAME_GERENTEDERECURSOSFINANCEIROS }}
            CYPRESS_USERNAME_GERENTEDETESOURARIA: ${{ secrets.CYPRESS_USERNAME_GERENTEDETESOURARIA }}
            CYPRESS_USERNAME_GERENTEDEFATURAMENTOAORECEBIMENTO: ${{ secrets.CYPRESS_USERNAME_GERENTEDEFATURAMENTOAORECEBIMENTO }}
            CYPRESS_USERNAME_GERENTEDENEGOCIACAOFINANCEIRA: ${{ secrets.CYPRESS_USERNAME_GERENTEDENEGOCIACAOFINANCEIRA }}
            CYPRESS_USERNAME_GERENTEADMINISTRATIVOCORPORATIVO: ${{ secrets.CYPRESS_USERNAME_GERENTEADMINISTRATIVOCORPORATIVO }}
            CYPRESS_USERNAME_GERENTEDEMANUTENCAO: ${{ secrets.CYPRESS_USERNAME_GERENTEDEMANUTENCAO }}
            CYPRESS_USERNAME_GERENTEJURIDICOA: ${{ secrets.CYPRESS_USERNAME_GERENTEJURIDICOA }}
            CYPRESS_USERNAME_GERENTEJURIDICOB: ${{ secrets.CYPRESS_USERNAME_GERENTEJURIDICOB }}
            CYPRESS_USERNAME_GERENTEDERECURSOSHUMANOSA: ${{ secrets.CYPRESS_USERNAME_GERENTEDERECURSOSHUMANOSA }}
            CYPRESS_USERNAME_GERENTEDERECURSOSHUMANOSB: ${{ secrets.CYPRESS_USERNAME_GERENTEDERECURSOSHUMANOSB }}
            CYPRESS_USERNAME_GERENTECOMERCIAL: ${{ secrets.CYPRESS_USERNAME_GERENTECOMERCIAL }}
            CYPRESS_USERNAME_GERENTEDETELEVENDAS: ${{ secrets.CYPRESS_USERNAME_GERENTEDETELEVENDAS }}
            CYPRESS_USERNAME_GERENTEDEMARKETING: ${{ secrets.CYPRESS_USERNAME_GERENTEDEMARKETING }}
            CYPRESS_USERNAME_GERENTEDEINTEGRACAO: ${{ secrets.CYPRESS_USERNAME_GERENTEDEINTEGRACAO }}
            CYPRESS_USERNAME_GERENTEADJUNTODEINTEGRACAO: ${{ secrets.CYPRESS_USERNAME_GERENTEADJUNTODEINTEGRACAO }}
            CYPRESS_USERNAME_GERENTEDENEGOCIOS: ${{ secrets.CYPRESS_USERNAME_GERENTEDENEGOCIOS }}
            CYPRESS_USERNAME_GERENTEADJDENEGOCIOS: ${{ secrets.CYPRESS_USERNAME_GERENTEADJDENEGOCIOS }}
            CYPRESS_USERNAME_GERENTEDESERVICOS: ${{ secrets.CYPRESS_USERNAME_GERENTEDESERVICOS }}
            CYPRESS_USERNAME_GERENTECX: ${{ secrets.CYPRESS_USERNAME_GERENTECX }}
            CYPRESS_USERNAME_GERENTEEAD: ${{ secrets.CYPRESS_USERNAME_GERENTEEAD }}
            CYPRESS_USERNAME_GERENTEDEDESIGNINSTRUCIONAL: ${{ secrets.CYPRESS_USERNAME_GERENTEDEDESIGNINSTRUCIONAL }}
            CYPRESS_USERNAME_GERENTEDEOPERACOES: ${{ secrets.CYPRESS_USERNAME_GERENTEDEOPERACOES }}
            CYPRESS_USERNAME_COORDENADORDEMATRICULA: ${{ secrets.CYPRESS_USERNAME_COORDENADORDEMATRICULA }}
            CYPRESS_USERNAME_COORDENADORADEPROCESSAMENTO: ${{ secrets.CYPRESS_USERNAME_COORDENADORADEPROCESSAMENTO }}
            CYPRESS_USERNAME_COORDENADORADMISSAODEPESSOAL: ${{ secrets.CYPRESS_USERNAME_COORDENADORADMISSAODEPESSOAL }}
            CYPRESS_USERNAME_COORDENADORADECOMPRAS: ${{ secrets.CYPRESS_USERNAME_COORDENADORADECOMPRAS }}
            CYPRESS_USERNAME_COORDENADOR_A_DECONTASAPAGAR: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DECONTASAPAGAR }}
            CYPRESS_USERNAME_COORDENADOR_A_BACKOFFICETESOURARIA: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_BACKOFFICETESOURARIA }}
            CYPRESS_USERNAME_COORDENADOR_A_FISCAL: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_FISCAL }}
            CYPRESS_USERNAME_COORDENADOR_A_CONTABILA: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_CONTABILA }}
            CYPRESS_USERNAME_COORDENADOR_A_CONTABILB: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_CONTABILB }}
            CYPRESS_USERNAME_COORDENADOR_A_DECONTROLADORIA: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DECONTROLADORIA }}
            CYPRESS_USERNAME_COORDENADOR_A_DEFATURAMENTO: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEFATURAMENTO }}
            CYPRESS_USERNAME_COORDENADOR_A_DECONTASARECEBER: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DECONTASARECEBER }}
            CYPRESS_USERNAME_COORDENADOR_A_DECONTROLEDECREDITO: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DECONTROLEDECREDITO }}
            CYPRESS_USERNAME_COORDENADOR_A_DEPAS: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEPAS }}
            CYPRESS_USERNAME_COORDENADOR_A_JURIDICO: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_JURIDICO }}
            CYPRESS_USERNAME_COORDENADOR_A_REMUNERACAOEBENEFICIOS: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_REMUNERACAOEBENEFICIOS }}
            CYPRESS_USERNAME_COORDENADOR_A_DEVIAGENS: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEVIAGENS }}
            CYPRESS_USERNAME_COORDENADOR_A_PLANEJVENDAS: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_PLANEJVENDAS }}
            CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGA: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGA }}
            CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGB: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGB }}
            CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGC: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGC }}
            CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGD: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DEMARKETINGD }}
            CYPRESS_USERNAME_COORDENADOR_A_DECOMPLIANCE: ${{ secrets.CYPRESS_USERNAME_COORDENADOR_A_DECOMPLIANCE }}
            CYPRESS_USERNAME_COORDENADORDEPERFORMANCE: ${{ secrets.CYPRESS_USERNAME_COORDENADORDEPERFORMANCE }}
            CYPRESS_USERNAME_SUPERVISORAFOLHAEREMUNERACAO: ${{ secrets.CYPRESS_USERNAME_SUPERVISORAFOLHAEREMUNERACAO }}
            CYPRESS_USERNAME_SUPERVISORADMISSAOEDESLIGAMENTO: ${{ secrets.CYPRESS_USERNAME_SUPERVISORADMISSAOEDESLIGAMENTO }}
            CYPRESS_USERNAME_SUPERVISOR_A_DATESOURARIA: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_DATESOURARIA }}
            CYPRESS_USERNAME_SUPERVISOR_A_DECONCILIACAO: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_DECONCILIACAO }}
            CYPRESS_USERNAME_SUPERVISOR_A_FATURAMENTO: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_FATURAMENTO }}
            CYPRESS_USERNAME_SUPERVISOR_A_DECONTROLEDECREDITO: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_DECONTROLEDECREDITO }}
            CYPRESS_USERNAME_SUPERVISOR_A_ACADEMICO: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_ACADEMICO }}
            CYPRESS_USERNAME_SUPERVISOR_A_ADMINISTRATIVOFINANCEIRO: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_ADMINISTRATIVOFINANCEIRO }}
            CYPRESS_USERNAME_SUPERVISOR_A_DESEGURANCA: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_DESEGURANCA }}
            CYPRESS_USERNAME_SUPERVISOR_A_DEVIAGENS: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_DEVIAGENS }}
            CYPRESS_USERNAME_SUPERVISOR_A_COMERCIAL: ${{ secrets.CYPRESS_USERNAME_SUPERVISOR_A_COMERCIAL }}
            CYPRESS_USERNAME_DIRETORADASECRETARIA: ${{ secrets.CYPRESS_USERNAME_DIRETORADASECRETARIA }}
            CYPRESS_USERNAME_GERENTEDETI: ${{ secrets.CYPRESS_USERNAME_GERENTEDETI }}
                 
        with:
          command: npm run test  