name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Gestao-de-Metas:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}  
          CYPRESS_USERNAME-CEO: ${{ secrets.CYPRESS_USERNAME-CEO }}
          CYPRESS_USERNAME-VICEPRESIDENTE: ${{ secrets.CYPRESS_USERNAME-VICEPRESIDENTE }}
          CYPRESS_USERNAME-DIRETORCRA: ${{ secrets.CYPRESS_USERNAME-DIRETORCRA }}
          CYPRESS_USERNAME-DIRETORADMISSAOAODESLIGAMENTO: ${{ secrets.CYPRESS_USERNAME-DIRETORADMISSAOAODESLIGAMENTO }}
          CYPRESS_USERNAME-DIRETORADJDESERVICOSFINANCEIROS: ${{ secrets.CYPRESS_USERNAME-DIRETORADJDESERVICOSFINANCEIROS }}
          CYPRESS_USERNAME-DIRETORADJDEFECHAMENTOAOREPORTE: ${{ secrets.CYPRESS_USERNAME-DIRETORADJDEFECHAMENTOAOREPORTE}}
          CYPRESS_USERNAME-DIRETOR-A-JURIDICO: ${{ secrets.CYPRESS_USERNAME-DIRETOR-A-JURIDICO}}
          CYPRESS_USERNAME-DIRETOR-A-DEMARKETING: ${{ secrets.CYPRESS_USERNAME-DIRETOR-A-DEMARKETING }}
          CYPRESS_USERNAME-DIRETOR-A-DETI: ${{ secrets.CYPRESS_USERNAME-DIRETOR-A-DETI }} 
          CYPRESS_USERNAME-DIRETOREAD: ${{ secrets.CYPRESS_USERNAME-DIRETOREAD }} 
          CYPRESS_USERNAME-DIRETORDEOPERACOESACADEMICAS: ${{ secrets.CYPRESS_USERNAME-DIRETORDEOPERACOESACADEMICAS }}
          CYPRESS_USERNAME-DIRETORDEPROGRAMASESTUDANTIS: ${{ secrets.CYPRESS_USERNAME-DIRETORDEPROGRAMASESTUDANTIS }}
          CYPRESS_USERNAME-DIRETORDEREGULACAO: ${{ secrets.CYPRESS_USERNAME-DIRETORDEREGULACAO }} 
          CYPRESS_USERNAME-DIRETORADJDEREGULACAOPESQUISAEEXTENSAO: ${{ secrets.CYPRESS_USERNAME-DIRETORADJDEREGULACAOPESQUISAEEXTENSAO }}
          CYPRESS_USERNAME-CFO: ${{ secrets.CYPRESS_USERNAME-CFO }}
          CYPRESS_USERNAME-DIRETORAADMINISTRATIVA: ${{ secrets.CYPRESS_USERNAME-DIRETORAADMINISTRATIVA }}
          CYPRESS_USERNAME-DIRETOR-A-DERECURSOSHUMANOS: ${{ secrets.CYPRESS_USERNAME-DIRETOR-A-DERECURSOSHUMANOS }}
          CYPRESS_USERNAME-GERENTEDEPROCESSAMENTO: ${{ secrets.CYPRESS_USERNAME-GERENTEDEPROCESSAMENTO }}
          CYPRESS_USERNAME-GERENTEDEATENDIMENTO: ${{ secrets.CYPRESS_USERNAME-GERENTEDEATENDIMENTO }}
          CYPRESS_USERNAME-GERENTEA: ${{ secrets.CYPRESS_USERNAME-GERENTEA }}
          CYPRESS_USERNAME-GERENTEB: ${{ secrets.CYPRESS_USERNAME-GERENTEB }}
          CYPRESS_USERNAME-GERENTEDERECURSOSFINANCEIROS: ${{ secrets.CYPRESS_USERNAME-GERENTEDERECURSOSFINANCEIROS }}
          CYPRESS_USERNAME-GERENTEDETESOURARIA: ${{ secrets.CYPRESS_USERNAME-GERENTEDETESOURARIA }}
          CYPRESS_USERNAME-GERENTEDEFATURAMENTOAORECEBIMENTO: ${{ secrets.CYPRESS_USERNAME-GERENTEDEFATURAMENTOAORECEBIMENTO }}
          CYPRESS_USERNAME-GERENTEDENEGOCIACAOFINANCEIRA: ${{ secrets.CYPRESS_USERNAME-GERENTEDENEGOCIACAOFINANCEIRA }}
          CYPRESS_USERNAME-GERENTEADMINISTRATIVOCORPORATIVO: ${{ secrets.CYPRESS_USERNAME-GERENTEADMINISTRATIVOCORPORATIVO }}
          CYPRESS_USERNAME-GERENTEDEMANUTENCAO: ${{ secrets.CYPRESS_USERNAME-GERENTEDEMANUTENCAO }}
          CYPRESS_USERNAME-GERENTEJURIDICOA: ${{ secrets.CYPRESS_USERNAME-GERENTEJURIDICOA }}
          CYPRESS_USERNAME-GERENTEJURIDICOB: ${{ secrets.CYPRESS_USERNAME-GERENTEJURIDICOB }}
          CYPRESS_USERNAME-GERENTEDERECURSOSHUMANOSA: ${{ secrets.CYPRESS_USERNAME-GERENTEDERECURSOSHUMANOSA }}
          CYPRESS_USERNAME-GERENTEDERECURSOSHUMANOSB: ${{ secrets.CYPRESS_USERNAME-GERENTEDERECURSOSHUMANOSB }}
          CYPRESS_USERNAME-GERENTECOMERCIAL: ${{ secrets.CYPRESS_USERNAME-GERENTECOMERCIAL }}
          CYPRESS_USERNAME-GERENTEDETELEVENDAS: ${{ secrets.CYPRESS_USERNAME-GERENTEDETELEVENDAS }}
          CYPRESS_USERNAME-GERENTEDEMARKETING: ${{ secrets.CYPRESS_USERNAME-GERENTEDEMARKETING }}
          CYPRESS_USERNAME-GERENTEDEINTEGRACAO: ${{ secrets.CYPRESS_USERNAME-GERENTEDEINTEGRACAO }}
          CYPRESS_USERNAME-GERENTEADJUNTODEINTEGRACAO: ${{ secrets.CYPRESS_USERNAME-GERENTEADJUNTODEINTEGRACAO }}
          CYPRESS_USERNAME-GERENTEDENEGOCIOS: ${{ secrets.CYPRESS_USERNAME-GERENTEDENEGOCIOS }}
          CYPRESS_USERNAME-GERENTEADJDENEGOCIOS: ${{ secrets.CYPRESS_USERNAME-GERENTEADJDENEGOCIOS }}
          CYPRESS_USERNAME-GERENTEDESERVICOS: ${{ secrets.CYPRESS_USERNAME-GERENTEDESERVICOS }}
          CYPRESS_USERNAME-GERENTECX: ${{ secrets.CYPRESS_USERNAME-GERENTECX }}
          CYPRESS_USERNAME-GERENTEEAD: ${{ secrets.CYPRESS_USERNAME-GERENTEEAD }}
          CYPRESS_USERNAME-GERENTEDEDESIGNINSTRUCIONAL: ${{ secrets.CYPRESS_USERNAME-GERENTEDEDESIGNINSTRUCIONAL }}
          CYPRESS_USERNAME-GERENTEDEOPERACOES: ${{ secrets.CYPRESS_USERNAME-GERENTEDEOPERACOES }}
          CYPRESS_USERNAME-COORDENADORDEMATRICULA: ${{ secrets.CYPRESS_USERNAME-COORDENADORDEMATRICULA }}
          CYPRESS_USERNAME-COORDENADORADEPROCESSAMENTO: ${{ secrets.CYPRESS_USERNAME-COORDENADORADEPROCESSAMENTO }}
          CYPRESS_USERNAME-COORDENADORADMISSAODEPESSOAL: ${{ secrets.CYPRESS_USERNAME-COORDENADORADMISSAODEPESSOAL }}
          CYPRESS_USERNAME-COORDENADORADECOMPRAS: ${{ secrets.CYPRESS_USERNAME-COORDENADORADECOMPRAS }}
          CYPRESS_USERNAME-COORDENADOR-A-DECONTASAPAGAR: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DECONTASAPAGAR }}
          CYPRESS_USERNAME-COORDENADOR-A-BACKOFFICETESOURARIA: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-BACKOFFICETESOURARIA }}
          CYPRESS_USERNAME-COORDENADOR-A-FISCAL: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-FISCAL }}
          CYPRESS_USERNAME-COORDENADOR-A-CONTABILA: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-CONTABILA }}
          CYPRESS_USERNAME-COORDENADOR-A-CONTABILB: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-CONTABILB }}
          CYPRESS_USERNAME-COORDENADOR-A-DECONTROLADORIA: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DECONTROLADORIA }}
          CYPRESS_USERNAME-COORDENADOR-A-DEFATURAMENTO: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEFATURAMENTO }}
          CYPRESS_USERNAME-COORDENADOR-A-DECONTASARECEBER: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DECONTASARECEBER }}
          CYPRESS_USERNAME-COORDENADOR-A-DECONTROLEDECREDITO: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DECONTROLEDECREDITO }}
          CYPRESS_USERNAME-COORDENADOR-A-DEP.A.S: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEP.A.S }}
          CYPRESS_USERNAME-COORDENADOR-A-JURIDICO: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-JURIDICO }}
          CYPRESS_USERNAME-COORDENADOR-A-REMUNERACAOEBENEFICIOS: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-REMUNERACAOEBENEFICIOS }}
          CYPRESS_USERNAME-COORDENADOR-A-DEVIAGENS: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEVIAGENS }}
          CYPRESS_USERNAME-COORDENADOR-A-PLANEJVENDAS: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-PLANEJVENDAS }}
          CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGA: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGA }}
          CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGB: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGB }}
          CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGC: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGC }}
          CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGD: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DEMARKETINGD }}
          CYPRESS_USERNAME-COORDENADOR-A-DECOMPLIANCE: ${{ secrets.CYPRESS_USERNAME-COORDENADOR-A-DECOMPLIANCE }}
          CYPRESS_USERNAME-COORDENADORDEPERFORMANCE: ${{ secrets.CYPRESS_USERNAME-COORDENADORDEPERFORMANCE }}
          CYPRESS_USERNAME-SUPERVISORAFOLHAEREMUNERACAO: ${{ secrets.CYPRESS_USERNAME-SUPERVISORAFOLHAEREMUNERACAO }}
          CYPRESS_USERNAME-SUPERVISORADMISSAOEDESLIGAMENTO: ${{ secrets.CYPRESS_USERNAME-SUPERVISORADMISSAOEDESLIGAMENTO }}
          CYPRESS_USERNAME-SUPERVISOR-A-DATESOURARIA: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-DATESOURARIA }}
          CYPRESS_USERNAME-SUPERVISOR-A-DECONCILIACAO: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-DECONCILIACAO }}
          CYPRESS_USERNAME-SUPERVISOR-A-FATURAMENTO: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-FATURAMENTO }}
          CYPRESS_USERNAME-SUPERVISOR-A-DECONTROLEDECREDITO: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-DECONTROLEDECREDITO }}
          CYPRESS_USERNAME-SUPERVISOR-A-ACADEMICO: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-ACADEMICO }}
          CYPRESS_USERNAME-SUPERVISOR-A-ADMINISTRATIVOFINANCEIRO: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-ADMINISTRATIVOFINANCEIRO }}
          CYPRESS_USERNAME-SUPERVISOR-A-DESEGURANCA: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-DESEGURANCA }}
          CYPRESS_USERNAME-SUPERVISOR-A-DEVIAGENS: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-DEVIAGENS }}
          CYPRESS_USERNAME-SUPERVISOR-A-COMERCIAL: ${{ secrets.CYPRESS_USERNAME-SUPERVISOR-A-COMERCIAL }}
          CYPRESS_USERNAME-DIRETORADASECRETARIA: ${{ secrets.CYPRESS_USERNAME-DIRETORADASECRETARIA }}
          CYPRESS_USERNAME-GERENTEDETI: ${{ secrets.CYPRESS_USERNAME-GERENTEDETI }}
        with:
          command: npm run test  